import type { Metadata } from "next";
import { ScreenSizeProvider } from "@/context/ScreenSizeContext";
import "./globals.css";
import {EditorProvider} from "@/context/EditorContext";


export const metadata: Metadata = {
  title: "OSPortfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ScreenSizeProvider>
            <EditorProvider>
                {children}
            </EditorProvider>
        </ScreenSizeProvider>
      </body>
    </html>
  );
}
