import type { Metadata } from "next";
import { ScreenSizeProvider } from "@/context/ScreenSizeContext";
import "./globals.css";


export const metadata: Metadata = {
  title: "OSPortfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ScreenSizeProvider>
        {children}
        </ScreenSizeProvider>
      </body>
    </html>
  );
}
